/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://7n36pwpcavcdzo7vcxkcktgmf4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-iib33zrz7rbp7i46tspvq33xhe",
    "aws_cognito_identity_pool_id": "us-east-1:9db808b9-250f-4e0c-8a38-e3bf7b5d9a00",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uvLGN8pRh",
    "aws_user_pools_web_client_id": "divp6ea7ud9oq6vci4jih9t5r",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_user_files_s3_bucket": "angulartour20a2cfda37a9491c9200e323d7159c40134458-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
